import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/app/_components/nav/Navbar';
import SessionWrapper from './_components/SessionWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <SessionWrapper>
                    <Navbar />
                    <main className="w-full lg:max-w-[1024px] bg-red-300 m-auto">
                        {children}
                    </main>
                </SessionWrapper>
            </body>
        </html>
    );
}
